def main ():
    import turtle
    turtle.fillcolor('grey')
    turtle.hideturtle
    
    #each line break is a new shape you can technically
    #unhashatg it all at once however the shapes will be jumbeled 

    # # conected dimonds
    # turtle.begin_fill()
    # turtle.left(45)
    # turtle.forward(400)
    # turtle.left(270)
    # turtle.forward(200)
    # turtle.left(270)
    # turtle.forward(200)
    # turtle.left(270)
    # turtle.forward(400)
    # turtle.left(90)
    # turtle.forward(200)
    # turtle.left(90)
    # turtle.forward(200)
    # turtle.end_fill()

    # #double triangle >:(
    # turtle.forward(168)
    # turtle.left(115)
    # turtle.forward(200)
    # turtle.left(130)
    # turtle.forward(200)
    # turtle.begin_fill()
    # turtle.left(144.5)
    # turtle.forward(99.57)
    # turtle.right(59)
    # turtle.forward(99.57)
    # turtle.end_fill()

    # #rectangle but 3D D:
    # turtle.left(90)
    # turtle.forward(50)
    # turtle.left(90)
    # turtle.forward(100)
    # turtle.right(90)
    # turtle.forward(50)
    # turtle.right(90)
    # turtle.forward(50)
    # turtle.right(90)
    # turtle.forward(100)
    # turtle.left(90)
    # turtle.forward(50)
    # turtle.left(135)
    # turtle.forward(141)
    # turtle.penup()
    # turtle.left(135)
    # turtle.forward(50)
    # turtle.pendown()
    # turtle.left(45)
    # turtle.forward(70.7)
    # turtle.penup()
    # turtle.left(45)
    # turtle.forward(50)
    # turtle.left(90)
    # turtle.forward(50)
    # turtle.left(45)
    # turtle.pendown()
    # turtle.forward(70.7)

    # #olimpic rings
    # turtle.circle(50)
    # turtle.penup()
    # turtle.forward(10)
    # turtle.pendown()
    # turtle.right(90)
    # turtle.circle(50)
    # turtle.left(90)
    # turtle.penup()
    # turtle.forward(110)
    # turtle.pendown()
    # turtle.circle(50)
    # turtle.right(90)
    # turtle.circle(50)
    # turtle.left(90)
    # turtle.penup()
    # turtle.forward(110)
    # turtle.pendown()
    # turtle.circle(50)

    # #A cicle on a grid
    # turtle.forward(200)
    # turtle.write('east')
    # turtle.right(180)
    # turtle.forward(200)
    # turtle.right(90)
    # turtle.forward(200)
    # turtle.write('north')
    # turtle.right(180)
    # turtle.forward(200)
    # turtle.right(90)
    # turtle.forward(200)
    # turtle.write('west')
    # turtle.right(180)
    # turtle.forward(200)
    # turtle.right(90)
    # turtle.forward(200)
    # turtle.write('south')
    # turtle.right(180)
    # turtle.forward(200)
    # turtle.right(90)
    # turtle.forward(35)
    # turtle.right(270)
    # turtle.circle(35)


    # #box with diganoals and dashed sides
    # turtle.pensize(5)
    # turtle.forward(0)
    # turtle.pensize(1)
    # turtle.right(45)
    # turtle.forward(200)
    # turtle.pensize(5)
    # turtle.forward(0)
    # turtle.pensize(1)
    # turtle.left(225)
    # turtle.forward(23.570226)
    # turtle.penup()
    # turtle.forward(47.14045)
    # turtle.pendown()
    # turtle.forward(47.14045)
    # turtle.penup()
    # turtle.forward(47.14045)
    # turtle.pendown()
    # turtle.forward(47.14045)
    # turtle.penup()
    # turtle.forward(47.14045)
    # turtle.pendown()
    # turtle.forward(23.570226)
    # turtle.pensize(5)
    # turtle.forward(0)
    # turtle.pensize(1)
    # turtle.right(135)
    # turtle.forward(400)
    # turtle.pensize(5)
    # turtle.forward(0)
    # turtle.pensize(1)
    # turtle.right(135)
    # turtle.forward(282.842712475)
    # turtle.right(180)
    # turtle.forward(282.842712475)
    # turtle.left(90)
    # turtle.forward(23.570226)
    # turtle.penup()
    # turtle.forward(47.14045)
    # turtle.pendown()
    # turtle.forward(47.14045)
    # turtle.penup()
    # turtle.forward(47.14045)
    # turtle.pendown()
    # turtle.forward(47.14045)
    # turtle.penup()
    # turtle.forward(47.14045)
    # turtle.pendown()
    # turtle.forward(23.570226)
    # turtle.pensize(5)
    # turtle.forward(0)
    # turtle.pensize(1)
    # turtle.left(90)
    # turtle.forward(282.842712475)
    # turtle.right(180)
    # turtle.forward(282.842712475)
    # turtle.right(135)
    # turtle.forward(200)

    
    #this always stays unhastaged
    turtle.exitonclick()
    

main()
